name: Publish to GitHub Packages

on:
  push:
    branches: [ master ]    

permissions:
  contents: read
  packages: write        

jobs:
  publish-ghp:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # 1) Package name must match GitHub username EXACTLY (case-sensitive)
      - name: Set correct package scope
        run: |
          npm pkg set name=@DRymers7/ts-to-proptypes

      # 2) Configure node with correct case-sensitive scope
      - name: Setup node for GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@DRymers7'
          always-auth: true

      # 3) Install & build
      - name: Install & build
        run: |
          npm ci
          npm run build

      # 4) Publish with correct authentication
      - name: Publish to GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish --registry https://npm.pkg.github.com --access public