name: Release

on:
  push:
    branches:
      - master  

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ——————————————————————————
      # 1) Publish to public npmjs.org
      # ——————————————————————————
      - name: Setup Node (npmjs)
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install & Build
        run: |
          npm ci
          npm run build

      - name: Publish to npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish

      # ——————————————————————————
      # 2) Publish to GitHub Packages
      # ——————————————————————————
      - name: Setup Node (GitHub Packages)
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@drymers'
          cache: 'npm'
          always-auth: true
          auth-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Packages
        run: npm publish
