# .github/workflows/release.yml
name: Release

on:
  push:
    branches:
      - master   # or "main"

permissions:
  contents: read
  packages: write    # gives GITHUB_TOKEN rights to publish packages

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # 1) Build against the public npm registry
      - name: Setup Node → npmjs.org
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install & Build
        run: |
          npm ci
          npm run build

      - name: Publish to npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish

      # 2) Build/Pub to GitHub Packages for @drymers/ scoped package
      - name: Setup Node → GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@drymers'
          cache: 'npm'

      - name: Publish to GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish
